[package]
name = "simple-restaurant-api"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
serde = { version = "1.0.117", features = ["derive"] }
serde_json = "*"
rand = "*"

[dev-dependencies]
actix-rt = "*"
tokio = { version = "*", features = ["macros", "rt-multi-thread"] }

