services:
  simple-restaurant-api:
    depends_on:
      mysql:
        condition: service_healthy
    build: .
    ports:
      - "8080:8080"

  mysql:
    image: mysql:8
    ports:
      - "3306:3306"
    hostname: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=passwd
    volumes:
         - ./scripts/db_init:/docker-entrypoint-initdb.d/:ro
    healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            timeout: 5s
            retries: 3